name: Run CI Tests
on: [push]
env:
  PLEDGE_VERSION: pledge-1.8.com
  PLEDGE_PATH: /opt/bin/pledge-1.8.com
jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          skip-cache: true
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Run Go Vet
        run: |
          make vet
      - name: Install Pledge
        run: |
          mkdir /opt/bin
          curl -L -o ${PLEDGE_PATH} https://github.com/shoenig/nomad-pledge-driver/releases/download/${PLEDGE_VERSION}/${PLEDGE_VERSION}
          chmod +x ${PLEDGE_PATH}
          ls -lha ${PLEDGE_PATH}
      - name: Run Go Test
        run: |
          make test
