name: Run CI Tests
on: [push]
env:
  GO_VERSION: ~1.19
  PLEDGE_VERSION: pledge-1.8.com
  PLEDGE_PATH: /opt/bin/pledge-1.8.com
jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Run Go Vet
        run: |
          make vet
      - name: Install Pledge
        run: |
          mkdir /opt/bin
          curl -L -o ${PLEDGE_PATH} https://github.com/shoenig/nomad-pledge-driver/releases/download/${PLEDGE_VERSION}/${PLEDGE_VERSION}
          chmod +x ${PLEDGE_PATH}
          ls -lha ${PLEDGE_PATH}
      - name: Run Go Test
        run: |
          make test
